# Generated by Django 3.1.5 on 2021-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulation',
            name='congratulation',
            field=models.CharField(max_length=1000),
        ),
    ]
